### ISSUE TITLE
Add a page listing known and fixed security issues and vulnerabilities.

### ISSUE THREAD

**Issue by fredjn** [eiffel-community/eiffel-community.github.io#14]
### Description
We need to have a page to list security issues and vulnerabilities that has been publicly disclosed for eiffel-community projects and repositories

### Motivation
Security and vulnerability information should be easily accessible to contributors and others in the eiffel-community.

### Exemplification
A security researcher finds that a vulnerability affects a project in the eiffel-community. The researcher can quickly check the security page on eiffel-community.github.io to see if a fix for the vulnerability has been released recently.

### Benefits
Easier to get an overview of what has been reported and fixed in the security context on the eiffel-community projects and repositories.

### Possible Drawbacks
None

**Comment by fdegir** [comment]
+1

/cc @eiffel-community/eiffel-community-maintainers
