### ISSUE TITLE
Archived summit pages have broken links

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-community.github.io#37]
### Description
More than one of the archived summit pages contain broken links and other references since they rely on relative links. Let's adjust the archived pages as well as /summit.html so that we don't repeat the same mistake the next time we move /summit.html to /archive/summit-whatever.html.

### Motivation
We obviously shouldn't have broken links. If we're to keep old summit pages they should render correctly.

### Exemplification
N/A

### Benefits
We can easily look at old summit pages.

### Possible Drawbacks
None.

**Comment by m-linner-ericsson** [comment]
Do we have any easy way to access the archived pages from the main io page or are the archives only for reference (e.g. you need to check them in the git repo)?

**Comment by magnusbaeck** [comment]
No, there are no links to them. So that's another problem that we could fix in the context of this issue.
