### ISSUE TITLE
Slack link in site footer not working

### ISSUE THREAD

**Issue by ericstengard** [eiffel-community/eiffel-community.github.io#58]
### Description

The slack link in the footer at https://eiffel-community.github.io/ isn't working. https://join.slack.com/t/eiffel-workspace/shared_invite/enQtOTI3MzEzMzY4Mzg0LTA3NDVmNjgzZjk1YTFjNzk5OWE4MjExYzE1ODU1NzA1YzY5MzhlZmYxZmIwMzhiM2ExOWM4ZGJlYzdkN2M5OTE

Same issue as #42 

### Motivation

It is difficult to join the slack channel without a working link.

### Exemplification

Cannot add a working link since I'm not in the channel.

### Benefits

Happy new Slack users

### Possible Drawbacks

None

**Comment by magnusbaeck** [comment]
Sigh. I thought the invite links would work longer than six months. We should look into if there's a way to create a more permanent invite. Thanks!

**Comment by magnusbaeck** [comment]
Oh, never mind. The PR that solves the previous issue didn't fix all invite links. The existing invite link used in community.html works fine but we also need to update includes/footer.html.
