### ISSUE TITLE
Broken link to sandbox/easy2use

### ISSUE THREAD

**Issue by e-backmark-ericsson** [eiffel-community/eiffel-community.github.io#6]
### Description
The link on the start page towards the Eiffel sandbox (easy2use) is not working.

### Motivation
Links should be correct

### Exemplification
A correct link would be good :)

### Benefits
People will find the Easy2Use sandbox.

### Possible Drawbacks
None

**Comment by e-pettersson-ericsson** [comment]
I guess this issue can be closed now since the code changes have been merged 😄
